### ISSUE TITLE
Server for ARM processors [Rpi4]

### ISSUE THREAD

**Issue by ProManiFest2122** [ottomated/CrewLink-server#165]
Just like in the title. Can you make version of server files (Docker) for ARM proccesors ?

**Comment by Jasbris** [comment]
Definitely would be a plus, however in the meantime I have successfully been running a CrewLink server on my Rpi4b running Ubuntu Server.

**Comment by Zedifuu** [comment]
You should just be able to **--build** it and docker will build from an environment compatible with **arm**, no ?
I run mine through docker compose to make my life easier.
### Here's my compose file:
```
version: '3'

services:
  crewlink:
    build: .
    container_name: crewlink
    ports:
      - 9736:9736
    environment:
      - TZ=${TZ}
      - ADDRESS=${URL}  #Specifies the server domain
      - NAME=${SERVNAME} #Specifies the server name
    restart: unless-stopped
```

### .env
```
TZ="Europe/London"
URL="https://crewlink.mywebsite.gg" # This can also be http://[your-public-ip-here]:[your-port] or https:// if you're using SSL
SERVNAME="Mr Internet Person's Crewlink"
```

Mine Hides behind a reverse-proxy, but if you want crewlink to handle the https, have a look at this guys comment:
https://github.com/ottomated/CrewLink-server/issues/102#issuecomment-755246390
